version: "3.8"

include:
  - path: ./docker-compose.service.yml

services:
  test-shared-adapters-server:
    build:
      context: .
      dockerfile: ./src/contexts/shared/adapters-server/Dockerfile
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/test
      - RABBIT_MQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    command: npm run test -w @shared/adapters-server
  test-helsa-modules:
    build:
      context: .
      dockerfile: ./src/contexts/helsa/Dockerfile
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    command: npm run test -w hospital
  helsa-principal-api:
    build:
      context: .
      dockerfile: ./src/apps/helsa/principal-api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    command: npm run start:test -w @helsa/principal-api
  helsa-consulting-room:
    build:
      context: .
      dockerfile: ./src/apps/helsa/consulting-room/Dockerfile
    ports:
      - "3002:3002"
    command: npm run dev -w @helsa/consulting-room
