version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./etc/data/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./etc/data/grafana/provisioning:/etc/grafana/provisioning/dashboards
      - ./etc/data/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
      - tempo
      - prometheus
      - otel-collector
  otel-collector:
    image: otel/opentelemetry-collector:0.61.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./etc/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4316:4318"   # OTLP HTTP receiver
  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    volumes:
      - loki-data:/tmp/loki
  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"  # tempo
      - "4318:4318"  # otlp http
      - "4317:4317"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo-data:/tmp
      - ./etc/tempo.yaml:/etc/tempo.yaml
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgresql
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
networks:
  monitoring:
volumes:
  grafana-data:
  loki-data:
  tempo-data:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
