version: "3.8"

services:
  shared:
    build:
      context: .
      dockerfile: ./src/contexts/shared/Dockerfile
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/test
      - RABBIT_MQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    command: npm run test -w @ducen/shared
  hospital:
    build:
      context: .
      dockerfile: ./src/contexts/hospital/Dockerfile
    command: npm run test -w @ducen/hospital
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
  principal-api:
    build:
      context: .
      dockerfile: ./src/apps/hospital/principal-api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    command: npm run start:test -w @ducen/hospital-principal-api
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
  redis:
    image: redis
    logging:
      driver: none
    ports:
      - "6378:6379"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    logging:
      driver: none
