export * from './chat.icon'
export * from './conf.icon'
export * from './dashboard.icon'
export * from './doctor'
export * from './facebook'
export * from './google'
export * from './heart'
export * from './linkedin.icon'
export * from './logout.icon'
export * from './missions.icon'
export * from './path.icon'
export * from './project.icon'
export * from './schedule.icon'
export * from './team.icon'
export * from './x'

